package org.domain.seam2mysql.entity;
// Generated 27/Fev/2012 17:12:47 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AplPerfil generated by hbm2java
 */
@Entity
@Table(name="apl_perfil"
    ,catalog="test"
)
public class AplPerfil  implements java.io.Serializable {


     private String codPerfil;
     private String descPerfil;
     private Set<AplUtil> aplUtils = new HashSet<AplUtil>(0);

    public AplPerfil() {
    }

	
    public AplPerfil(String codPerfil) {
        this.codPerfil = codPerfil;
    }
    public AplPerfil(String codPerfil, String descPerfil, Set<AplUtil> aplUtils) {
       this.codPerfil = codPerfil;
       this.descPerfil = descPerfil;
       this.aplUtils = aplUtils;
    }
   
     @Id 

    
    @Column(name="cod_perfil", unique=true, nullable=false, length=20)
    @NotNull
    @Length(max=20)
    public String getCodPerfil() {
        return this.codPerfil;
    }
    
    public void setCodPerfil(String codPerfil) {
        this.codPerfil = codPerfil;
    }

    
    @Column(name="desc_perfil", length=45)
    @Length(max=45)
    public String getDescPerfil() {
        return this.descPerfil;
    }
    
    public void setDescPerfil(String descPerfil) {
        this.descPerfil = descPerfil;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aplPerfil")
    public Set<AplUtil> getAplUtils() {
        return this.aplUtils;
    }
    
    public void setAplUtils(Set<AplUtil> aplUtils) {
        this.aplUtils = aplUtils;
    }




}


