package org.domain.seam2mysql.entity;
// Generated 20/Fev/2012 16:31:07 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;

/**
 * AplPerfilId generated by hbm2java
 */
@Embeddable
public class AplPerfilId  implements java.io.Serializable {


     private String codPerfil;
     private String descPerfil;

    public AplPerfilId() {
    }

    public AplPerfilId(String codPerfil, String descPerfil) {
       this.codPerfil = codPerfil;
       this.descPerfil = descPerfil;
    }
   


    @Column(name="cod_perfil", length=20)
    @Length(max=20)
    public String getCodPerfil() {
        return this.codPerfil;
    }
    
    public void setCodPerfil(String codPerfil) {
        this.codPerfil = codPerfil;
    }


    @Column(name="desc_perfil", length=100)
    @Length(max=100)
    public String getDescPerfil() {
        return this.descPerfil;
    }
    
    public void setDescPerfil(String descPerfil) {
        this.descPerfil = descPerfil;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AplPerfilId) ) return false;
		 AplPerfilId castOther = ( AplPerfilId ) other; 
         
		 return ( (this.getCodPerfil()==castOther.getCodPerfil()) || ( this.getCodPerfil()!=null && castOther.getCodPerfil()!=null && this.getCodPerfil().equals(castOther.getCodPerfil()) ) )
 && ( (this.getDescPerfil()==castOther.getDescPerfil()) || ( this.getDescPerfil()!=null && castOther.getDescPerfil()!=null && this.getDescPerfil().equals(castOther.getDescPerfil()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodPerfil() == null ? 0 : this.getCodPerfil().hashCode() );
         result = 37 * result + ( getDescPerfil() == null ? 0 : this.getDescPerfil().hashCode() );
         return result;
   }   


}


