package org.domain.seam2mysql.entity;
// Generated 27/Fev/2012 17:12:47 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AplUtil generated by hbm2java
 */
@Entity
@Table(name="apl_util"
    ,catalog="test"
)
public class AplUtil  implements java.io.Serializable {


     private String utilizador;
     private AplPerfil aplPerfil;
     private String passwd;
     private String unidOrg;
     private Date dataUltAlt;

    public AplUtil() {
    }

	
    public AplUtil(String utilizador, AplPerfil aplPerfil, Date dataUltAlt) {
        this.utilizador = utilizador;
        this.aplPerfil = aplPerfil;
        this.dataUltAlt = dataUltAlt;
    }
    public AplUtil(String utilizador, AplPerfil aplPerfil, String passwd, String unidOrg, Date dataUltAlt) {
       this.utilizador = utilizador;
       this.aplPerfil = aplPerfil;
       this.passwd = passwd;
       this.unidOrg = unidOrg;
       this.dataUltAlt = dataUltAlt;
    }
   
     @Id 

    
    @Column(name="utilizador", unique=true, nullable=false, length=100)
    @NotNull
    @Length(max=100)
    public String getUtilizador() {
        return this.utilizador;
    }
    
    public void setUtilizador(String utilizador) {
        this.utilizador = utilizador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_perfil", nullable=false)
    @NotNull
    public AplPerfil getAplPerfil() {
        return this.aplPerfil;
    }
    
    public void setAplPerfil(AplPerfil aplPerfil) {
        this.aplPerfil = aplPerfil;
    }

    
    @Column(name="passwd", length=45)
    @Length(max=45)
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    
    @Column(name="unid_org", length=45)
    @Length(max=45)
    public String getUnidOrg() {
        return this.unidOrg;
    }
    
    public void setUnidOrg(String unidOrg) {
        this.unidOrg = unidOrg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_ult_alt", nullable=false, length=19)
    @NotNull
    @Version
    public Date getDataUltAlt() {
        return this.dataUltAlt;
    }
    
    public void setDataUltAlt(Date dataUltAlt) {
        this.dataUltAlt = dataUltAlt;
    }




}


