package org.domain.seam2mysql.entity;
// Generated 27/Fev/2012 17:12:47 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="test"
)
public class City  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String countryCode;
     private String district;
     private int population;

    public City() {
    }

    public City(String name, String countryCode, String district, int population) {
       this.name = name;
       this.countryCode = countryCode;
       this.district = district;
       this.population = population;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Name", nullable=false, length=35)
    @NotNull
    @Length(max=35)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="CountryCode", nullable=false, length=3)
    @NotNull
    @Length(max=3)
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    
    @Column(name="District", nullable=false, length=25)
    @NotNull
    @Length(max=25)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="Population", nullable=false)
    public int getPopulation() {
        return this.population;
    }
    
    public void setPopulation(int population) {
        this.population = population;
    }




}


