package org.domain.seam2mysql.entity;
// Generated 27/Fev/2012 17:12:47 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="country"
    ,catalog="test"
)
public class Country  implements java.io.Serializable {


     private String code;
     private String name;
     private String continent;
     private String region;
     private float surfaceArea;
     private Short indepYear;
     private int population;
     private Float lifeExpectancy;
     private Float gnp;
     private Float gnpold;
     private String localName;
     private String governmentForm;
     private String headOfState;
     private Integer capital;
     private String code2;
     private boolean selected;

    public Country() {
    }

	
    public Country(String code, String name, String continent, String region, float surfaceArea, int population, String localName, String governmentForm, String code2, boolean selected) {
        this.code = code;
        this.name = name;
        this.continent = continent;
        this.region = region;
        this.surfaceArea = surfaceArea;
        this.population = population;
        this.localName = localName;
        this.governmentForm = governmentForm;
        this.code2 = code2;
        this.selected = selected;
    }
    public Country(String code, String name, String continent, String region, float surfaceArea, Short indepYear, int population, Float lifeExpectancy, Float gnp, Float gnpold, String localName, String governmentForm, String headOfState, Integer capital, String code2, boolean selected) {
       this.code = code;
       this.name = name;
       this.continent = continent;
       this.region = region;
       this.surfaceArea = surfaceArea;
       this.indepYear = indepYear;
       this.population = population;
       this.lifeExpectancy = lifeExpectancy;
       this.gnp = gnp;
       this.gnpold = gnpold;
       this.localName = localName;
       this.governmentForm = governmentForm;
       this.headOfState = headOfState;
       this.capital = capital;
       this.code2 = code2;
       this.selected = selected;
    }
   
     @Id 

    
    @Column(name="Code", unique=true, nullable=false, length=3)
    @NotNull
    @Length(max=3)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="Name", nullable=false, length=52)
    @NotNull
    @Length(max=52)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Continent", nullable=false, length=13)
    @NotNull
    @Length(max=13)
    public String getContinent() {
        return this.continent;
    }
    
    public void setContinent(String continent) {
        this.continent = continent;
    }

    
    @Column(name="Region", nullable=false, length=26)
    @NotNull
    @Length(max=26)
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }

    
    @Column(name="SurfaceArea", nullable=false, precision=10)
    public float getSurfaceArea() {
        return this.surfaceArea;
    }
    
    public void setSurfaceArea(float surfaceArea) {
        this.surfaceArea = surfaceArea;
    }

    
    @Column(name="IndepYear")
    public Short getIndepYear() {
        return this.indepYear;
    }
    
    public void setIndepYear(Short indepYear) {
        this.indepYear = indepYear;
    }

    
    @Column(name="Population", nullable=false)
    public int getPopulation() {
        return this.population;
    }
    
    public void setPopulation(int population) {
        this.population = population;
    }

    
    @Column(name="LifeExpectancy", precision=3, scale=1)
    public Float getLifeExpectancy() {
        return this.lifeExpectancy;
    }
    
    public void setLifeExpectancy(Float lifeExpectancy) {
        this.lifeExpectancy = lifeExpectancy;
    }

    
    @Column(name="GNP", precision=10)
    public Float getGnp() {
        return this.gnp;
    }
    
    public void setGnp(Float gnp) {
        this.gnp = gnp;
    }

    
    @Column(name="GNPOld", precision=10)
    public Float getGnpold() {
        return this.gnpold;
    }
    
    public void setGnpold(Float gnpold) {
        this.gnpold = gnpold;
    }

    
    @Column(name="LocalName", nullable=false, length=45)
    @NotNull
    @Length(max=45)
    public String getLocalName() {
        return this.localName;
    }
    
    public void setLocalName(String localName) {
        this.localName = localName;
    }

    
    @Column(name="GovernmentForm", nullable=false, length=45)
    @NotNull
    @Length(max=45)
    public String getGovernmentForm() {
        return this.governmentForm;
    }
    
    public void setGovernmentForm(String governmentForm) {
        this.governmentForm = governmentForm;
    }

    
    @Column(name="HeadOfState", length=60)
    @Length(max=60)
    public String getHeadOfState() {
        return this.headOfState;
    }
    
    public void setHeadOfState(String headOfState) {
        this.headOfState = headOfState;
    }

    
    @Column(name="Capital")
    public Integer getCapital() {
        return this.capital;
    }
    
    public void setCapital(Integer capital) {
        this.capital = capital;
    }

    
    @Column(name="Code2", nullable=false, length=2)
    @NotNull
    @Length(max=2)
    public String getCode2() {
        return this.code2;
    }
    
    public void setCode2(String code2) {
        this.code2 = code2;
    }

    
    @Column(name="selected", nullable=false)
    public boolean isSelected() {
        return this.selected;
    }
    
    public void setSelected(boolean selected) {
        this.selected = selected;
    }




}


