package org.domain.seam2mysql.entity;
// Generated 27/Fev/2012 17:12:47 by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Countrylanguage generated by hbm2java
 */
@Entity
@Table(name="countrylanguage"
    ,catalog="test"
)
public class Countrylanguage  implements java.io.Serializable {


     private CountrylanguageId id;
     private String isOfficial;
     private float percentage;

    public Countrylanguage() {
    }

    public Countrylanguage(CountrylanguageId id, String isOfficial, float percentage) {
       this.id = id;
       this.isOfficial = isOfficial;
       this.percentage = percentage;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="countryCode", column=@Column(name="CountryCode", nullable=false, length=3) ), 
        @AttributeOverride(name="language", column=@Column(name="Language", nullable=false, length=30) ) } )
    @NotNull
    public CountrylanguageId getId() {
        return this.id;
    }
    
    public void setId(CountrylanguageId id) {
        this.id = id;
    }

    
    @Column(name="IsOfficial", nullable=false, length=2)
    @NotNull
    @Length(max=2)
    public String getIsOfficial() {
        return this.isOfficial;
    }
    
    public void setIsOfficial(String isOfficial) {
        this.isOfficial = isOfficial;
    }

    
    @Column(name="Percentage", nullable=false, precision=4, scale=1)
    public float getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(float percentage) {
        this.percentage = percentage;
    }




}


