package org.domain.seam2mysql.entity;
// Generated 27/Fev/2012 17:12:47 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.security.management.RoleName;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    ,catalog="test"
)
public class Role  implements java.io.Serializable {


     private String roleId;
     private String roleName;
     private Set<User> users = new HashSet<User>(0);

    public Role() {
    }

	
    public Role(String roleId, String roleName) {
        this.roleId = roleId;
        this.roleName = roleName;
    }
    public Role(String roleId, String roleName, Set<User> users) {
       this.roleId = roleId;
       this.roleName = roleName;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="role_id", unique=true, nullable=false, length=100)
    @NotNull
    @Length(max=100)
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    
    @Column(name="role_name", nullable=false, length=100)
    @NotNull
    @Length(max=100)
    @RoleName
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="roles")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


